#!/bin/bash

typeset -g CHPWD_COMMAND=""
_chpwd_hook() {
	local _shopts _shopt
	_shopts=$(shopt -p)
	shopt -s nullglob

	local f

	# run commands in CHPWD_COMMAND variable on dir change
	if [[ "$PREVPWD" != "$PWD" ]]; then
		local IFS=$';'
		for f in $CHPWD_COMMAND; do
			"$f"
		done
		unset IFS
	fi
	# refresh last working dir record
	export PREVPWD="$PWD"
	while read -r _shopt; do $_shopt; done <<< "$_shopts"
}
PROMPT_COMMAND="_chpwd_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
_rec_dir() {
	echo "$PWD" > ~/.last_cd_to
}
CHPWD_COMMAND=_rec_dir

if [[ $NO_CD != 1 ]]; then
	cd "$(< ~/.last_cd_to)" || true
fi
